### ISSUE TITLE
Implement graphs

### ISSUE THREAD

**Issue by arendjr** [autometrics-dev/vscode-autometrics#12]
With https://github.com/autometrics-dev/vscode-autometrics/pull/10, the foundation is being laid for implementing graphs inside the VS Code extension. This is a tracking issue for progress. Also feel free to leave ideas and suggestions related to graphs here.

- [x] Create a TS library for rendering graphs. This will be based on the charts in our Studio product and open-sourced in the `fiberplane` repository. Done: https://github.com/fiberplane/fiberplane/pull/48
- [x] Basic integration of the graph library into our extension. Done: https://github.com/autometrics-dev/vscode-autometrics/pull/22
- [x] Update the design, making sure VS Code themes work well
  - [x]  add toggle for showing/hiding promql
  - [x] add additional queries for called by metrics
  - [x] add timerange selector/controls
  - [x] make top bar sticky
  - [x] fix resize issue where graphs don't shrink when window is resized
  - [x] charts: 
    - [x] use vscode theme colors
    - [x] x-axis should better respect the width (sometimes the tick text overlaps)
  - [x] promql code block:
    - [x] add copy button
